version: '3'

services:

  tor:
      image: haxxinen/alpine_tor
      container_name: tor
      build:
        context: .
      ports:
        - '127.0.0.1:9050:9050'
      volumes:
        - ./supervisord.conf:/etc/supervisord.conf
        - /tmp/tor/:/var/lib/tor
